sonar.projectKey=gigacode-vscode
sonar.host.url=https://sbt-sonarqube.sigma.sbrf.ru
sonar.sources=src,webview-ui 
sonar.tests=src,webview-ui
sonar.test.inclusions=src/test/**/*.test.ts,webview-ui/**/*.test.ts
sonar.exclusions=src/test/**/*.test.ts,webview-ui/**/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test_results.xml
